stateDiagram-v2
    [*] --> Off
    state On {
        [*] --> On_Idle
        On_Idle --> On_Working: Work|Log("Action: Starting Work")
        On_Working --> On_Idle: Stop|Log("Action: Stopping Work")
    }
    Off --> On: PowerOn|Log("Action: Powering On")
    On --> Off: PowerOff|Log("Action: Powering Off")
    Off --> End: Finish|Log("Action: Finishing")
